### ISSUE TITLE
JSON_EXTRACT() function not exist issue with MySQL lower versions (to 5.6)

### ISSUE THREAD

**Issue by AjithLalps** [codezero-be/laravel-unique-translation#11]
My hosting provider does not support MySQL version 5.7. Maximum supported version is 5.6.46. So I'm facing JSON_EXTRACT and JSON_UNQUOTE function does not exist error. 

Is there any fix on that?

**Comment by ivanvermeyen** [comment]
Hi, 

MySQL5.7 is the. minimum supported version at the moment, because we select a specific translation in a column that contains JSON:

https://github.com/codezero-be/laravel-unique-translation/blob/1bf82dceacf3244953d1a68564381f5709795d81/src/UniqueTranslationValidator.php#L230-L233

Perhaps it is possible to use a different query that doesn't use the JSON syntax, but I haven't thought about that yet. Any ideas?

**Comment by ivanvermeyen** [comment]
Well this didn't seem to break any tests, so might be a viable solution...

```php
return DB::connection($connection)->table($table)->where($column, 'LIKE', "%\"{$locale}\":\"{$value}\"%");
```

I'll push the commit so you can try it out.

**Comment by AjithLalps** [comment]
Can you release a version with this?. It will be very helpful.

**Comment by ivanvermeyen** [comment]
Tagged in 3.3.0 👍

**Comment by AjithLalps** [comment]
Thank you 😄
