### ISSUE TITLE
UniqueTranslationRule is ignored - Laravel 8

### ISSUE THREAD

**Issue by benjaminhaeberli** [codezero-be/laravel-unique-translation#19]
Hello @ivanvermeyen!

First, thanks for developing this great package. I'm trying to use it on a Laravel 8 project I started recently, but I can't get it to work. I'm pretty sure I forgot something stupid, but I've been looking for a week and even showed it to a colleague, but we can't find an error. Maybe you can help me?

When I try to update a post with the same slug as another (or create once with the same slug as another), the **UniqueTranslationRule** rule doesn't detect it. My form request **App\Http\Requests\Admin\PostRequest** has this `rules` function :

```php
public function rules()
    {
        return [
            'post.title' => 'required|string',
            'post.slug' => ['required', 'max:2000', UniqueTranslationRule::for('posts', 'slug'), 'regex:/^([a-z0-9\-\/]*)$/'],
            'post.category_id' => ['nullable', 'numeric', Rule::exists('categories', 'id')
                ->where('deleted_at', NULL)->where('type', Category::TYPE_POST)],
        ];
    }
```

Things I checked :
- Spatie\laravel-translatable is working (all data are saved in JSON in the database)
- I call `use CodeZero\UniqueTranslation\UniqueTranslationRule;` at the beginning of the file
- I remove and resinstalled the package with `composer require codezero/laravel-unique-translation`

Thanks in advance ! 🙏

**Comment by ivanvermeyen** [comment]
Hello,

I had to refresh my memory for a second, but there is a problem when using nested attribute syntax like `post.slug`.
You can also use this syntax to submit multiple translations, like `slug.en`.
So in your case that would become`post.slug.en`, etc.

I have to detect the locale in the validation rule. The way I do this by getting any string after a dot.
Because a locale can be anything, there is no way to distinguish it from a field name.
If you just submit a `slug` attribute, then there is no dot in the attribute name and the app's locale is used.

https://github.com/codezero-be/laravel-unique-translation/blob/a26017dfd2222b421b17aa799ab91a5563eca93d/src/UniqueTranslationValidator.php#L126-L131

I don't know if there is any other way to handle this that supports nested arrays...

Edit:

One workaround that should work is be to add the locale to the form field: `name="post[slug][en]"`
Then validate `post.slug.*`

**Comment by benjaminhaeberli** [comment]
Hello @ivanvermeyen,

Your explanation is very clear, I understood the problem and if I use `post.slug.*` it works fine! It's an architecture issue on my side: currently, my requests validate the slug for the current language of the user with `app()->getLocale()`. However, there will be only one form per resource in the back-office, so I actually have to support the validation of several slugs at the same time (the entities are shared between the different languages, only some fields like the title and the slug are translatable). 

Thanks for your help, I'll do the corrections on my side 👍 By the way I'll also implement your [**laravel-localized-routes**](https://github.com/codezero-be/laravel-localized-routes) package for the front-office, it looks great 😎
