### ISSUE TITLE
Support spatie/nova-translatable

### ISSUE THREAD

**Issue by gldrenthe89** [codezero-be/laravel-unique-translation#7]
How to use this with Laravel Nova?

**Comment by ivanvermeyen** [comment]
Hi,

I don't use Laravel Nova, so I don't really know how it works under the hood.
But this package works just like any other validation rule.

**Comment by ivanvermeyen** [comment]
Closing for now... If here is still a problem with this package in combination with Nova, feel free to reopen and provide some more details. I'd be happy to look into it.

**Comment by pa-bouly** [comment]
I think when we use [spatie/laravel-translatable](https://github.com/spatie/laravel-translatable/), with Nova we have to use [/spatie/nova-translatable](https://github.com/spatie/nova-translatable/) . 

We should be able to use laravel-unique-translation as follow : 
```
Text::make(__('Slug'), 'slug')
->creationRules('unique_translation:posts,slug')
->updateRules('unique_translation:posts,slug,{{resourceId}}'),
```
But right now it only works with the App locale because the function [getAttributeNameAndLocale](https://github.com/codezero-be/laravel-unique-translation/blob/587cbd3077827622ca6139fe581d9cfff20d1514/src/UniqueTranslationValidator.php#L68) should explode differently like : 
```
        $parts = explode('_', $attribute);
        $name = $parts[1];
        $locale = $parts[2] ?? App::getLocale();
```
because of [this line](https://github.com/spatie/nova-translatable/blob/5ce6f11ad0dadd460d3c55dc04b153fd16d13ee8/src/Translatable.php#L121)  in the nova-translatable package

**Comment by ivanvermeyen** [comment]
@pa-bouly  Thanks for the insight.

It seems that the locale won't always be at index 2 tho, if the original attribute name contains underscores. So we need to strip off the first part and use the very last part as the locale.

Would any project use both the underscore and dot notation?

We can either...
- check for a valid locale with both strategies and use the first one found
- add an option to enable the Nova strategy (project wide)

I think I like the first approach the best, giving the dot notation priority and using the underscore as "fallback".

Any thoughts?

**Edit:**
Locales can't have underscores tho :(
`en_US` wouldn't work... Does Nova support that?

**Comment by pa-bouly** [comment]
Yes, i like the first approach too, easier to implement and doesn't need one more option to configure.
And this way, a project would be able to use both the underscore and dot notation.

Btw the [setMissingErrorMessages](https://github.com/codezero-be/laravel-unique-translation/blob/587cbd3077827622ca6139fe581d9cfff20d1514/src/UniqueTranslationValidator.php#L44) will have to change a bit as well I think to be able to have a key like 
```"translations_{$name}_{$locale}.{$rule}",```

Thanks for your quick response @ivanvermeyen  ;)

**Comment by ivanvermeyen** [comment]
Yes, that would be one additional message to add.
Good catch :)

To wrap it up:

We would require the locale to be either...

- the second value when using the dot notation,
- or the last value when using the underscore notation (and `translations_` would be stripped off).

**Some limitations apply when using the underscore notation...**

- the locale itself cannot contain an underscore, because it's just impossible to know (we can't compare with supported locales).
- you can not use dot (array) and underscore notation at the same time; when a dot is in the attribute name, the second attribute part is assumed to be the locale...

Do you think this is acceptable?
At first glance, I don't see any other complications.

I have no way to test this with Nova, so I am relying on your feedback to make this work :)

**Comment by pa-bouly** [comment]
Yep it looks good to me !
No problem @ivanvermeyen  , i would be happy to help and test it !

**Comment by ivanvermeyen** [comment]
@pa-bouly  Just pushed a commit to dev-master.
If you can verify everything works as expected, I'll tag it :)

**Comment by ivanvermeyen** [comment]
@pa-bouly I've also updated the readme with a small Nova section.
Is it clear enough? Feel free to add some more info if it's not. :)

**Comment by pa-bouly** [comment]
I just tested on one of my projects and it works well! :+1: 
![Capture d’écran de 2020-04-06 18-05-35](https://user-images.githubusercontent.com/10745291/78579490-4b489500-7831-11ea-9d3f-772772869e89.png)
And the readme looks good to me too, thank you @ivanvermeyen :)

**Comment by ivanvermeyen** [comment]
Cool!
Tagged in release 3.2.0 👍
